using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using MofCoordinateDemo.Models;

namespace MofCoordinateDemo.Automation1;

/// <summary>
/// Runs only on the upper-level client PC. The scanner server never creates or
/// changes process coordinates; it receives this generated source verbatim.
/// </summary>
public sealed partial class AeroScriptGenerator
{
    public string Generate(
        CoordinateInput input,
        IReadOnlyList<CellCommand> commands,
        AeroScriptGenerationOptions options)
    {
        ArgumentNullException.ThrowIfNull(input);
        ArgumentNullException.ThrowIfNull(commands);
        ArgumentNullException.ThrowIfNull(options);

        if (commands.Count == 0)
        {
            throw new InvalidOperationException("AeroScript를 생성할 가공 좌표가 없습니다.");
        }

        if (!double.IsFinite(options.CoordinatedSpeed) || options.CoordinatedSpeed <= 0)
        {
            throw new InvalidOperationException("Coordinated speed는 0보다 큰 유한값이어야 합니다.");
        }

        var headNumbers = commands.Select(command => command.ScannerIndex).Distinct().OrderBy(index => index).ToArray();
        var axesByHead = headNumbers.ToDictionary(
            head => head,
            head => (
                X: ResolveAxisName(options.AxisXTemplate, head),
                Y: ResolveAxisName(options.AxisYTemplate, head)));

        var source = new StringBuilder(Math.Max(4096, commands.Count * 120));
        source.AppendLine("// Generated by the A1 upper-level client. Do not regenerate on the scanner server.");
        source.AppendLine($"// Generated UTC: {DateTimeOffset.UtcNow:O}");
        source.AppendLine($"// Review camera center: ({Format(input.ReviewCenterGlobalX)}, {Format(input.ReviewCenterGlobalY)})");
        source.AppendLine($"// Dynamic process offset: ({Format(input.ProcessOffsetGlobalX)}, {Format(input.ProcessOffsetGlobalY)})");
        source.AppendLine($"// Reverse-MOF target count: {commands.Count}");
        source.AppendLine("// IMPORTANT: laser/PSO triggering must be added only after the equipment-specific interlock sequence is validated.");
        source.AppendLine();
        source.AppendLine("program");

        foreach (var head in headNumbers)
        {
            var axes = axesByHead[head];
            source.AppendLine($"    var $scannerAxesH{head}[] as axis = [{axes.X}, {axes.Y}]");
        }

        source.AppendLine();
        if (options.EnableAxes)
        {
            foreach (var head in headNumbers)
            {
                source.AppendLine($"    Enable($scannerAxesH{head})");
            }

            source.AppendLine();
        }

        source.AppendLine("    SetupTaskTargetMode(TargetMode.Absolute)");
        source.AppendLine($"    SetupCoordinatedSpeed({Format(options.CoordinatedSpeed)})");
        source.AppendLine();

        foreach (var command in commands.OrderBy(command => command.MofSequence))
        {
            source.AppendLine(
                $"    // MOF #{command.MofSequence}: {command.CellIndex}, H{command.ScannerIndex}, " +
                $"Stage=({Format(command.ProcessStageX)}, {Format(command.ProcessStageY)})");
            source.AppendLine(
                $"    MoveLinear($scannerAxesH{command.ScannerIndex}, " +
                $"[{Format(command.Gx)}, {Format(command.Gy)}], {Format(options.CoordinatedSpeed)})");
        }

        if (options.DisableAxesAtEnd)
        {
            source.AppendLine();
            foreach (var head in headNumbers)
            {
                source.AppendLine($"    Disable($scannerAxesH{head})");
            }
        }

        source.AppendLine("end");
        return source.ToString();
    }

    private static string ResolveAxisName(string template, int head)
    {
        var axisName = (template ?? "").Replace("{0}", head.ToString(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        if (!AxisIdentifierRegex().IsMatch(axisName))
        {
            throw new InvalidOperationException($"Axis 이름 '{axisName}'은 유효한 AeroScript 식별자가 아닙니다.");
        }

        return axisName;
    }

    private static string Format(double value) => value.ToString("0.######", CultureInfo.InvariantCulture);

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.CultureInvariant)]
    private static partial Regex AxisIdentifierRegex();
}
